library(lubridate)
df <- read.csv("household_power_consumption.txt", sep=";")
df[,1] <- as.Date(strptime(with(df, df[ , "Date"]), "%d/%m/%Y"))
df <- df[df$Date >= as.Date("2007-02-01") & df$Date <= as.Date("2007-02-02"), ]
df[ , 3] <- as.numeric(as.character(df$Global_active_power))
df[ , 7] <- as.numeric(as.character(df$Sub_metering_1))
df[ , 8] <- as.numeric(as.character(df$Sub_metering_2))
df[ , 9] <- as.numeric(as.character(df$Sub_metering_3))
Sys.setlocale("LC_TIME", "English")
png("plot3.png",width=480,height=480,units="px")
plot( strptime(paste(df$Date, df$Time), "%Y-%m-%d %H:%M:%S"), df$Sub_metering_1, type = "n", ylab ="Energy sub metering", xlab ="")
lines( strptime(paste(df$Date, df$Time), "%Y-%m-%d %H:%M:%S"), df$Sub_metering_1)
lines( strptime(paste(df$Date, df$Time), "%Y-%m-%d %H:%M:%S"), df$Sub_metering_2, col="red")
lines( strptime(paste(df$Date, df$Time), "%Y-%m-%d %H:%M:%S"), df$Sub_metering_3, col="blue")
legend("topright",  names(df)[7:9], col=c("black","red","blue"), lwd = 1)
dev.off()