library(lubridate)
df <- read.csv("household_power_consumption.txt", sep=";")
df[,1] <- as.Date(strptime(with(df, df[ , "Date"]), "%d/%m/%Y"))
df <- df[df$Date >= as.Date("2007-02-01") & df$Date <= as.Date("2007-02-02"), ]
df[ , 3] <- as.numeric(as.character(df$Global_active_power))
Sys.setlocale("LC_TIME", "English")
png("plot2.png",width=480,height=480,units="px")
plot( strptime(paste(df$Date, df$Time), "%Y-%m-%d %H:%M:%S"), df$Global_active_power, type = "n", ylab ="Global Active Power (kilowatts)", xlab ="")
lines( strptime(paste(df$Date, df$Time), "%Y-%m-%d %H:%M:%S"), df$Global_active_power)
dev.off()