library(lubridate)
df <- read.csv("household_power_consumption.txt", sep=";")
df[,1] <- as.Date(strptime(with(df, df[ , "Date"]), "%d/%m/%Y"))
df <- df[df$Date >= as.Date("2007-02-01") & df$Date <= as.Date("2007-02-02"), ]
df[ , 3] <- as.numeric(as.character(df$Global_active_power))
df[ , 7] <- as.numeric(as.character(df$Sub_metering_1))
df[ , 8] <- as.numeric(as.character(df$Sub_metering_2))
df[ , 9] <- as.numeric(as.character(df$Sub_metering_3))
df[ , 5] <- as.numeric(as.character(df$Voltage))
df[ , 4] <- as.numeric(as.character(df$Global_reactive_power))
Sys.setlocale("LC_TIME", "English")
png("plot4.png",width=480,height=480,units="px")
par(mfrow=c(2,2))
plot( strptime(paste(df$Date, df$Time), "%Y-%m-%d %H:%M:%S"), df$Global_active_power, type = "n", ylab ="Global Active Power (kilowatts)", xlab ="")
lines( strptime(paste(df$Date, df$Time), "%Y-%m-%d %H:%M:%S"), df$Global_active_power)
plot( strptime(paste(df$Date, df$Time), "%Y-%m-%d %H:%M:%S"), df$Voltage, type = "n", ylab ="Voltage", xlab ="datetime")
lines( strptime(paste(df$Date, df$Time), "%Y-%m-%d %H:%M:%S"), df$Voltage)
plot( strptime(paste(df$Date, df$Time), "%Y-%m-%d %H:%M:%S"), df$Sub_metering_1, type = "n", ylab ="Energy sub metering", xlab ="")
lines( strptime(paste(df$Date, df$Time), "%Y-%m-%d %H:%M:%S"), df$Sub_metering_1)
lines( strptime(paste(df$Date, df$Time), "%Y-%m-%d %H:%M:%S"), df$Sub_metering_2, col="red")
lines( strptime(paste(df$Date, df$Time), "%Y-%m-%d %H:%M:%S"), df$Sub_metering_3, col="blue")
legend("topright",  names(df)[7:9], col=c("black","red","blue"), lwd = 1, bty = "n")
plot( strptime(paste(df$Date, df$Time), "%Y-%m-%d %H:%M:%S"), df$Global_reactive_power, type = "n", ylab ="Global_reactive_power", xlab ="datetime")
lines( strptime(paste(df$Date, df$Time), "%Y-%m-%d %H:%M:%S"), df$Global_reactive_power)
dev.off()

